[project]
name = "staff-eng-prep"
version = "0.1.0"
description = "Staff Engineer Interview Study Notes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "mkdocs-roamlinks-plugin>=0.3.2",
]
